scope: pg_cluster
namespace: /db/
name: node3

restapi:
  listen: 10.131.0.29:8008
  connect_address: 10.131.0.29:8008

etcd:
  hosts: 10.131.0.26:2379,10.131.0.18:2379,10.131.0.29:2379

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        wal_level: replica
        hot_standby: "on"
        wal_keep_segments: 8
        max_wal_senders: 5
        max_replication_slots: 5
        checkpoint_timeout: 30

  initdb:
    - encoding: UTF8

  pg_hba:
    - host replication replicator 10.131.0.26/32 md5
    - host replication replicator 10.131.0.18/32 md5
    - host replication replicator 10.131.0.29/32 md5
    - host all all 0.0.0.0/0 md5

postgresql:
  listen: 0.0.0.0:5432
  connect_address: 10.131.0.29:5432
  data_dir: /var/lib/postgresql/16/main
  bin_dir: /usr/lib/postgresql/16/bin
  pgpass: /tmp/pgpass
  authentication:
    replication:
      username: replicator
      password: RepPass1
    superuser:
      username: postgres
      password: PgPass1
    rewind:
      username: rewind_user
      password: RwPass1

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false
